/**
* Finflux-Self
* Finflux-Self APIs
*
* The version of the OpenAPI document: 0.9
* Contact: develop@finflux.co
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package co.finflux.openapi.self


import com.squareup.moshi.Json

/**
 * 
 * @param value 
 */

data class ApiErrorMessageArg (
    @Json(name = "value")
    val value: kotlin.Any? = null
)

