/**
* Finflux-Self
* Finflux-Self APIs
*
* The version of the OpenAPI document: 0.9
* Contact: develop@finflux.co
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package co.finflux.openapi.self


import com.squareup.moshi.Json

/**
 * 
 * @param firstName first name associated with the user
 * @param lastName last name associated with the user
 * @param emailAddress email id of the user
 * @param mobileNumber mobileNo associated with the user
 * @param password password associated with the user
 * @param organizationName Name of the organization
 * @param userName username associated with the user
 * @param officeId Id associated to office to which user is mapped
 * @param repeatPassword repeatPassword for validating user password
 * @param isSelfServiceUser Set to true if the user is a self user
 * @param sendPasswordToEmail Set to true if password has to be dent to email
 */

data class SignUpRequestPayload (
    /* first name associated with the user */
    @Json(name = "firstName")
    val firstName: kotlin.String,
    /* last name associated with the user */
    @Json(name = "lastName")
    val lastName: kotlin.String,
    /* email id of the user */
    @Json(name = "emailAddress")
    val emailAddress: kotlin.String,
    /* mobileNo associated with the user */
    @Json(name = "mobileNumber")
    val mobileNumber: kotlin.String,
    /* password associated with the user */
    @Json(name = "password")
    val password: kotlin.String,
    /* Name of the organization */
    @Json(name = "organizationName")
    val organizationName: kotlin.String,
    /* username associated with the user */
    @Json(name = "userName")
    val userName: kotlin.String? = null,
    /* Id associated to office to which user is mapped */
    @Json(name = "officeId")
    val officeId: kotlin.Long? = null,
    /* repeatPassword for validating user password */
    @Json(name = "repeatPassword")
    val repeatPassword: kotlin.String? = null,
    /* Set to true if the user is a self user */
    @Json(name = "isSelfServiceUser")
    val isSelfServiceUser: kotlin.Boolean? = null,
    /* Set to true if password has to be dent to email */
    @Json(name = "sendPasswordToEmail")
    val sendPasswordToEmail: kotlin.Boolean? = null
)

