/**
* Finflux-Self
* Finflux-Self APIs
*
* The version of the OpenAPI document: 0.9
* Contact: develop@finflux.co
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package co.finflux.openapi.self


import com.squareup.moshi.Json

/**
 * 
 * @param resourceId 
 */

data class SignUpOTPResponsePayload (
    @Json(name = "resourceIdentifier")
    val resourceIdentifier: kotlin.String? = null
)

